### ISSUE TITLE
Filtering duplicates

### ISSUE THREAD

**Issue by nsearls-bu** [hicsail/fhs-online-inquiry-system-frontend#16]
It is possible to add a second identical filter. Clicking on one opens the dropdown for both. I think there needs to be a check to not allow adding duplicate filters.

**Comment by nsearls-bu** [comment]
This only applies to some filters

**Comment by wenhwang97** [comment]
@nsearls-bu Is it happening at the deployed server or localhost? Do you still remember the steps to reproduce the error?

**Comment by nsearls-bu** [comment]
On the prod deployment. For example: add postmortem interval, then go back to the dropdown list. Postmortem interval is still on the list and still be added.

**Comment by nsearls-bu** [comment]
And this is without hitting apply

**Comment by wenhwang97** [comment]
OK. Found the issue you mentioned. Here are the steps to reproduce the issue:

1. Add any filters
2. Clear the input box
3. **When the input box is empty, hit "backspace" again OR click "X" button within the input box**
4. Filters will reappear in the dropdown, and can be added again

I will work on that.

**Comment by nsearls-bu** [comment]
That is accurate. Can be done with only mouseclick if user clicks "X" within the input box in step 3 as well.

**Comment by wenhwang97** [comment]
Issue addressed in recent PR #21
