### ISSUE TITLE
Dynamic chart resizing

### ISSUE THREAD

**Issue by nsearls-bu** [hicsail/fhs-online-inquiry-system-frontend#20]
Filter box and download buttons don't resize within container when window size is changed

**Comment by nsearls-bu** [comment]
https://github.com/hicsail/fhs-online-inquiry-system-frontend/assets/128721102/523a95a3-09e8-40a3-9d0c-ab2739fbd54f

**Comment by wenhwang97** [comment]
Switched to different design
